# Site settings
title: Shape2040
description: "Here we could have a mission statment sort of thing that would give visitors broad view of what this whole thing is about."
baseurl: ""
url: "http://Shape2040.github.io/" # the base hostname & protocol for your site
future: true
# Build settings
markdown: kramdown

host: 0.0.0.0
port: 4000
