# Site settings
title: Great Scott!
description: "Great Scott! The 2016 Comprehensive Plan for Scott County, Kentucky"
baseurl: ""
url: "http://greatscottplan.com/" # the base hostname & protocol for your site
future: true
# Build settings
markdown: kramdown

host: 0.0.0.0
port: 4000
